# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/GepingBookstoreOrder/api/categories
Accept: application/json

###
# curl 'http://localhost:8080/GepingBookstoreOrder/api/orders'
#  -H 'Accept: */*'
#  -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7'
#  -H 'Cache-Control: max-age=0'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:8081'
#  -H 'Referer: http://localhost:8081/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1002,"title":"The Road","author":"Cormac McCarthy","description":"science book","price":99,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1001},"quantity":3}]},"customerForm":{"name":"asdf","address":"asdf","phone":"5718991111","email":"lkj@vt.edu","ccNumber":"4444333322221111","ccExpiryMonth":11,"ccExpiryYear":2022}}'
#  --compressed
POST http://localhost:8080/GepingBookstoreOrder/api/orders
Accept: */*
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Origin: http://localhost:8081
Referer: http://localhost:8081/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1002,
          "title": "The Road",
          "author": "Cormac McCarthy",
          "description": "science book",
          "price": 99,
          "rating": 0,
          "isPublic": false,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 3
      }
    ]
  },
  "customerForm": {
    "name": "asdf",
    "address": "asdf",
    "phone": "5718991111",
    "email": "lkj@vt.edu",
    "ccNumber": "4444333322221111",
    "ccExpiryMonth": 11,
    "ccExpiryYear": 2022
  }
}

###

